### ISSUE TITLE
Issue with running the demo 

### ISSUE THREAD

**Issue by Mitko88** [frostweep/PUN2VoiceWebGLUnity#3]
I've tried to ruin the demo, and I get an error that getMicrophoneDevices function is missing.

![image](https://user-images.githubusercontent.com/8992310/88240007-4537d080-ccc9-11ea-92eb-97f2c4057313.png)

**Comment by Mitko88** [comment]
I had for MicrophoneWebGLLibrary all platforms enabled to support, instead of having only WebGL ticked.

**Comment by frostweep** [comment]
Hello,

good to know that issue fixed!

Thanks for supporting us!

Lemme know if you will have any other questions.

Best Regards
