### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by MasterSilver** [frostweep/PUN2VoiceWebGLUnity#4]
Please can you help me, I bought the plugin for microphone in webgl, I run this example without errors but it does not work, photon is well configured with the license and WebSocketSecure, but still it still does not work.

I uploaded the example in
https://intreestudios.com/voice/

**Comment by frostweep** [comment]
Hello,

which unity version you use?


could you replace this file and check again? (Assets / FrostweepGames /
MicrophoneWebGL / Plugins / WebGL / MicrophoneWebGLLibrary.jslib)
(file attached)

Best Regards

**Comment by MasterSilver** [comment]
The version I use is 2019.2.21f1, I can't see the attachment that you tell me.

**Comment by frostweep** [comment]
please write me on email: frostweep@gmail.com
