### ISSUE TITLE
Not working in the editor and the build ! Kindly help in fixing the issue

### ISSUE THREAD

**Issue by ram66351** [frostweep/PUN2VoiceWebGLUnity#6]
I have purchased the Microphone WebGL build library from the asset store (https://assetstore.unity.com/packages/tools/input-management/microphone-webgl-library-79989). But this demo is not working at all even in the editor.

**Comment by artem-shyriaiev** [comment]
Hello,

contact me at frostweep@gmail.com or in our discord: https://discord.gg/TZdhnWy

I'll help you setup project to make it workable on your side.

**Comment by ram66351** [comment]
Sent you an inbox message :)
