### ISSUE TITLE
Voice Break and lag in voice chat 

### ISSUE THREAD

**Issue by karishmaibentos** [frostweep/PUN2VoiceWebGLUnity#8]
Hello ,

I have downloaded the Voice Pro - WebGL, Mobile, Desktop from the unity asset store. Now I am facing some issues
1. voice chat delay--- comes after 2-3 sec minimum
2. voice break ---not clear when multiple players join the same room(5 players I have used)
3. Sometimes unable to listen in Voice chat .....voice delay was intolerable.
please help me to fix my issues.....ASAP

**Comment by frostweep** [comment]
hello.

2 known issues I know and completely related to Unity is: AudioClip.SetData
doesnt work in WebGL properly which cause issues with sound lag when played
chunk ended and begins to play new chunk which is workaround for webgl
currently. second thing is that for some reason when js code is running
under unity canvas it cause delays in receiving data from microphone from
browser(its interesting that if device has better CPU or app running with
high fps then delay is small). first thing related to Voice Pro asset and
second thing is to Microphone Pro asset.
we still investigating how we could improve both assets based on experience
from completely new product we announced for webgl

"not clear when multiple players join the same room(5 players I have used)"
-> you have to manage by own code to which room players joins by providing
same room name and be sure to be at the same region.

Best Regards

**Comment by frostweep** [comment]
this issue isnt related to that plugin since its not Voice Pro

**Comment by karishmaibentos** [comment]
No its Voice pro which i have downloaded from asset store https://assetstore.unity.com/packages/tools/input-management/voice-pro-webgl-mobile-desktop-169274

**Comment by frostweep** [comment]
this repository completely another solution and not connected to Voice Pro anyhow.
